version: "3"

services:
    pihole:
      container_name: pihole
      image: pihole/pihole:latest
      restart: unless-stopped
      network_mode: "host"
      environment:
        TZ: 'Europe/Berlin'
        WEBPASSWORD: 'sicheresPasswort'  # hier euer Passwort eingeben
      volumes:
         - 'E:/SeePi/pihole/pihole/:/etc/pihole/' # /home/sebi/SeePi/
         - 'E:/SeePi/pihole/dnsmasq/:/etc/dnsmasq.d/' # /home/sebi/SeePi/
      dns:
        - 127.0.0.1
        - 1.1.1.1