version: "3.8"

services: 
  nginx:
    image: nginx:latest
    container_name: seepi_nginx
    restart: on-failure
    volumes: 
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports: 
      - "8080:8080"
    networks: 
      - "seepi-network"
  
  shiny-test:
    image: raspi-shiny:latest
    container_name: seepi_shinytest
    build:
      context: shiny_test
    restart: on-failure
    depends_on: 
      - nginx
    networks: 
      - "seepi-network"
    expose: 
      - 8080

networks: 
  seepi-network: